services:
  app:
    image: ghcr.io/katosamuelraymond/creative-cube-next:latest
    restart: always
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.next-app.rule=Host(`next.conquerer.org`)"
      - "traefik.http.routers.next-app.entrypoints=websecure"
      - "traefik.http.routers.next-app.tls.certresolver=le"
      - "traefik.http.services.next-app.loadbalancer.server.port=3000"
      - "traefik.http.services.next-app.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.next-app.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true